name: html workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # ✅ Add the runner
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME_HTML }}
          password: ${{ secrets.DOCKER_PASSWORD_HTML }}

      - name: Build Docker Image
        run: |
          docker build -t nooraaj/my-html-app:latest .

      - name: Push to Docker Hub
        run: |
          docker push nooraaj/my-html-app:latest
